#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5
# Switch to workspace 6 with Super + 0

# Switch to workspace 7, 8, 9 with Super + {7,8,9}
bspc config key super-8 --focus 8
bspc config key super-9 --focus 9
bspc config key super-0 --focus 0


~/.config/polybar/launch.sh

#rules
bspc rule -a XClipboard state=floating

bspc config window_gap 5
# enable if you are noob
/* bspc config focus_follows_pointer false */
bspc config single_monocle true
bspc config gapless_monocle false    # equivalent of i3 smart gaps, which only applies gaps if theres more than 1 window
bspc config borderless_monocle false 
bspc config border_width 2
bspc config normal_border_color "#ffffff"
bspc config focused_border_color "#b624ff"
bspc config split_ratio 0.50
bspc config presel_feedback_color "#1ABB9B"
bspc config urgent_border_color "#dd2727"

sxhkd &
feh --randomize --bg-fill ~/Pictures/Wallpaper/* &
picom --config $HOME/.config/picom/picom.conf &
dunst &
